### ISSUE TITLE
Add a `wait_with_output` equivalent

### ISSUE THREAD

**Issue by luser** [alexcrichton/tokio-process#2]
I'd love to use this in sccache as I refactor it to use tokio, but we need to capture the process stdout/stderr. It'd be useful to have an equivalent to the standard library's `wait_with_output` to accomplish this. I don't need the outputs as streams, just getting a `std::process::Output` as the future result would be fine.

sccache is not actually using `wait_with_output` currently, because sometimes it wants to also write some input to standard input, so I wrote a `wait_with_input_output` function:
https://github.com/mozilla/sccache/blob/decd0b1a99ab33af0ef83ef7e57cea6a7ede0f73/src/compiler/compiler.rs#L458

**Comment by alexcrichton** [comment]
I believe to do this we need a way to get nonblocking stdin/stdout handles to do asynchronous reads/writes on. Unfortunately that's not possible yet on Windows but I hope to implement this feature soon!

**Comment by alexcrichton** [comment]
I'll do this as soon as https://github.com/alexcrichton/tokio-process/pull/1 merges which [is in turn](https://github.com/alexcrichton/tokio-process/pull/1#issuecomment-266885679) blocked on some [more support in mio](https://github.com/carllerche/mio/pull/504).

**Comment by alexchandel** [comment]
@alexcrichton Basically with the Windows terminal, you can either poll the Console Input handle for events (which include keyboard, mouse, menu, focus-changing, and window-resizing events) with `WaitForSingleObject` or `WaitForMultipleObjects`, and theoretically filter out the key-down or key-up events.

**HOWEVER** this means line-discipline, line-editing, and line-echoing won't work (i.e. people will complain that they don't see what they type, and that backspace and arrow keys don't work), because in Windows ALL of that is handled by the child process in userspace (via some Win32 DLL), and is only done when you call (blocking) `ReadConsole` or `getline` (which calls `ReadConsole` under the hood) or any equivalent blocking call that reads `stdin`. The process that draws the actual terminal window, `conhost.exe`, does no line-discipline/keyboard-processing whatsoever. (Nor does `cmd.exe` do anything when it's running a child process)

So the other option in Windows is to start a second thread and call `ReadConsole`, and then pass lines you read back to the main thread.

Note that the Console Input is not compatible with IOCP because it's not a character stream that can be split into lines, it's keyboard events. However you might be able to do non-blocking IO on the messages coming from the second thread, if `mio` supports channels. Then you've effectively spent one thread to wrap the Windows Console into a normal line stream.

**Comment by alexcrichton** [comment]
@alexchandel it sounds like you're mostly referring to managing the current process's stdin/stdout with Tokio? This issue, however, is for managing a child process's piped stdin/stdout with Tokio, so I'm not able to make the connection yet...
