### ISSUE TITLE
doc doesn't show that ChildStdout implements AsyncRead and ChildStdin implements AsyncWrite

### ISSUE THREAD

**Issue by little-dude** [alexcrichton/tokio-process#22]
https://docs.rs/tokio-process/0.2.0/tokio_process/struct.ChildStdout.html
https://docs.rs/tokio-process/0.2.0/tokio_process/struct.ChildStdin.html

I cloned the repo with the intention to add these traits, but they are already there.

**Comment by ipetkov** [comment]
To give some historical context, a 0.2 version was released some time back but was yanked (maybe @alexcrichton can fill in the gap here), while all other development continued on the 0.1 series as if 0.2 never existed.

It's pretty unfortunate that crates.io and docs.rs prefer defaulting to the highest version number to display. The reason why the 0.2.0 docs don't show `Async{Read, Write}` impls is because they don't exist in that version, but they are definitely present in 0.1.4.

I'm not sure of any other way to get around the misleading docs other than bumping semver

**Comment by alexcrichton** [comment]
Gah :(

I released 0.2 but then figured it'd be better to keep everything tokio-* at 0.1 as long as I could, so I quickly went back to release a new 0.1.x series with just some local hacks to preserve backwards compatibility. I'm not sure how to update the docs on docs.rs though:(

**Comment by ipetkov** [comment]
It seems that docs.rs has an issue for hiding yanked versions: onur/docs.rs#112

**Comment by alexchandel** [comment]
Does this mean it's possible to asynchronously read from the child's stdout, or presumably frame the byte stream from the child's stdout with LineCodec?

**Comment by little-dude** [comment]
Yes. Same for `ChildStderr`.

**Comment by alexchandel** [comment]
@little-dude got a quick example of reading lines from it? :) the docs are a little sparse.

**Comment by little-dude** [comment]
@alexchandel in one of my crate a want to have a stream of lines for stderr, so I have this: https://github.com/little-dude/xrl/blob/ba269756045dbe84a27a9f1e724e8dd5676501ed/src/core.rs#L81-L118

Does that help?

**Comment by aep** [comment]
this doesn't seem to work for me. the stdout stream immediately ends, leaving the process defunct.

```
let mut c = Command::new("ls")
            .stdout(Stdio::piped())
             .spawn_async(&self.handle)
             .expect("command failed to start");

let stdout = c.stdout().take().unwrap();
let stream = Box::new(FramedRead::new(stdout, LinesCodec::new())) as Box<Stream<Item = String, Error = std::io::Error>>;


```

**Comment by ipetkov** [comment]
We now have a milestone for tracking a true `0.2`/`0.2.1` release which will resolve the issue with docs.rs when it is published, so going to close this
