### ISSUE TITLE
Can't use tokio-process via a `TcpServer` - Consider `Remote` instead of `Handle`

### ISSUE THREAD

**Issue by petehayes102** [alexcrichton/tokio-process#23]
I'm trying to use this crate as part of an API, which is exposed via a `tokio_proto::TcpServer`. The problem I'm encountering is that `Handle`s are not sendable. This means I'm left with a `Remote`, which is not enough for me to consume `spawn_async` et. al.

However, you don't (nor do your dependent crates) need a `Handle`. Firstly this crate calls `tokio-signal::Signal::new()`, which invokes `Handle::spawn()`, though that can also be called via `Remote` with the same effect. Secondly this crate calls `tokio_core::PollEvented::new`, which downgrades it to a `Remote` anyway. Can these not all just be `Remote`s?

One way of overcoming this without breaking changes could be by implementing `Deref<Remote>` for `Handle` and changing the fn signatures to use `Remote`, though I haven't actually tested this myself so I might be missing something?

**Comment by alexcrichton** [comment]
Thanks for the report! 

I think this is required though as the tokio-signal crate currently [spawns a task](https://github.com/alexcrichton/tokio-signal/blob/3fa92b4f0ddb1303ebaa1f26c13a8238316afb4e/src/unix.rs#L362) which requires a handle rather than a remote, and in general we can't change the `PollEvented` handle for now. You may be interested in tokio-rs/tokio-rfcs#3 though which would solve this as well!

**Comment by petehayes102** [comment]
Doesn't `Remote` also have the ability to [spawn tasks](https://docs.rs/tokio-core/0.1.10/tokio_core/reactor/struct.Remote.html#method.spawn)?

Anyway, tokio-rfcs#3 looks really cool. If only I had a time machine! 😄 Thanks for the heads up mate.

**Comment by alexcrichton** [comment]
Hm true yeah, but I think it's probably best to wait for handles to become Send regardless
