### ISSUE TITLE
Child Stdout doesn't update often enough

### ISSUE THREAD

**Issue by alexchandel** [alexcrichton/tokio-process#24]
I have a child process that outputs a highly variable number of lines per second. However, I'm finding that, when I attempt to process it with a FramedRead and a simple line codec, `decode` is almost never called when data should be available. Instead, it's called only after about 8192 bytes have been written, which seems to indicate an 8K buffer somewhere (I'm using stable rust, latest tokio, & macOS 10.13.1).

Is this a tokio buffer? Can it be configured from tokio?

**Comment by ipetkov** [comment]
Hi @alexchandel, thanks for the report!

[Diving] through [the code] for `FramedRead` shows that `tokio-io` is setting an 8K [initial buffer]. If the child process sends a high volume of data its possible that `FramedRead` will wait until its buffer is filled before attempting any decoding. I'm not too familiar with the `FramedRead` APIs so it may be worth asking on the `tokio-io` issue tracker about how this can be configured.

Going to close this since there isn't much we can do here because `tokio-process` does not do any buffering of the child's output itself. Feel free to reopen if you have any other questions or issues! 

[Diving]: https://github.com/tokio-rs/tokio-io/blob/c3792323db212b9bb5d36415af810adad3a9d315/src/framed_read.rs#L116
[the code]: https://github.com/tokio-rs/tokio-io/blob/c3792323db212b9bb5d36415af810adad3a9d315/src/framed_read.rs#L218
[initial buffer]: https://github.com/tokio-rs/tokio-io/blob/c3792323db212b9bb5d36415af810adad3a9d315/src/framed_read.rs#L105

**Comment by alexchandel** [comment]
Turns out it wasn't due to FramedRead's buffer, though the 8K is a funny coincidence, but apparently due to the default OS buffering on the pipe. I was able to change one child process to autoflush, but there's another I can't edit.
