### ISSUE TITLE
Support process forking

### ISSUE THREAD

**Issue by ebkalderon** [alexcrichton/tokio-process#47]
The current implementation of `tokio-process` supports only spawning external commands via `std::process::Command`. Would it be feasible to expose support for `fork()` on Unix-like platforms as well? It would be nice to use `tokio-process` to fork off multiple worker subprocesses from the main one and run them to completion in a reactor core.

**Comment by ipetkov** [comment]
Hi @ebkalderon, thanks for the report!

To my knowledge, [calling `fork()` without calling `exec()`](http://www.evanjones.ca/fork-is-dangerous.html) is generally [discouraged](https://mikeash.com/pyblog//friday-qa-2012-01-20-fork-safety.html) because it can lead to deadlocks among other intermittent problems if the `fork` occurs while another thread is holding a lock for example. For complex programs with many dependencies (which may or may not be using threads under the hood), it becomes very difficult to ensure such bugs don't crop up.

Can you elaborate a bit more on your use case for just forking workers instead of using a separate thread in the same process?

**Comment by ebkalderon** [comment]
Well, I aim to run each forked process in a `chroot` under a potentially different user and a restricted set permissions, which as far as I know cannot be achieved with in-process threads.

**Comment by ipetkov** [comment]
Gotcha! One possible technique to use here is re-`exec`ing as the same process (with an extra flag/env var to denote it should operate as a worker) which would avoid the above pitfalls.

Would this work for you?

For example, this can be done using 

```rust
Command::new(::std::env::current_exe().unwrap())
    .arg("--worker")
    .before_exec(|| chroot_and_change_user())
    .spawn_async()
```

**Comment by ebkalderon** [comment]
That might just work! It seems pretty straightforward to implement, given the current design of the application I'm writing. I appreciate the useful links and the tip. I think this issue is safe to close for now, but should I run into any stumbling blocks regarding `tokio-process` in this particular context, I might reopen it. Thanks for the help!
